noun1 = input("Type in a noun.")
noun2 = input("Type in a noun.")
adj1 = input("Type in a adjective.")
noun3 = input("Type in a noun.")
adj2 = input("Type in a adjective.")
plural_noun = input("Type in a plural noun.")
noun4 = input("Type in a noun.")
number1 = input("Type in a number.")
shape1_plural = input("Type in a plural shape.")
food1 = input("Type in a food.")
adj3 = input("Type in a type of adjective.")

print("Pizza was invented by a" + noun1)
print("To make a pizza, you need to take a lump of" + noun2)
print("and make a thin, round" + adj1 + noun3)
print("Then you cover it with" + adj2)
print("sauce, " + adj2)
print("cheese, and fresh chopped" + plural_noun)
print("Next you have to bake it in a very hot" + noun4)
print("When it is done, cut it into" + number1 + shape1_plural)
print("Personally, my favorite pizza flavor is" + food1)
print("That is because it tastes very" + adj3)
